# source: https://github.com/TimonVS/pr-labeler-action
new feature: ['feature/*', 'feat/*']
enhancement: ['enhancement/*', 'enhance/*', "enh/*"]
bug fix: ['fix/*', 'bugfix/*', "bug-fix/*"]
documentation: ['docs/*', 'doc/*', 'documentation/*']