version: '3'
services:
  fylr-elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: fylr-elastic
    environment:
      - node.name=fylr-elastic
      - cluster.name=fylr-elastic
      - cluster.initial_master_nodes=fylr-elastic
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    command: /bin/sh -c "./bin/elasticsearch-plugin list | grep -q analysis-icu || ./bin/elasticsearch-plugin install analysis-icu; /usr/local/bin/docker-entrypoint.sh"
    volumes:
      - ./data/elastic:/usr/share/elasticsearch/data
    networks:
      - fylr

  fylr-minio:
    image: "minio/minio"
    container_name: "fylr-minio"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    volumes:
      - ./data/minio:/data
    command: server /data
    depends_on:
      - fylr-elastic
    networks:
      - fylr

  execserver:
    image: docker.fylr.io/fylr/fylr:main
    container_name: execserver
    restart: always
    environment:
      FYLR_LOGGER_LEVEL: info
      FYLR_LOGGER_TIMEFORMAT: "2006-01-02T15:04:05Z07:00"
      FYLR_SERVICES_EXECSERVER_ADDR: ":8070"
    depends_on:
      - fylr-elastic
      - fylr-minio
    networks:
      - fylr
    volumes:
      - "./config/execserver:/fylr/config"

  fylr:
    image: docker.fylr.io/fylr/fylr:main
    hostname: fylr.localhost
    container_name: fylr
    restart: always
    environment:
      FYLR_NAME: "sqlite3"
      FYLR_EXTERNALURL: "http://fylr.localhost:8080"
      FYLR_SERVICES_WEBAPP_ADDR: ":8080"
      FYLR_SERVICES_WEBAPP_REVERSEPROXY_API: "http://fylr.localhost:8081"
      FYLR_SERVICES_WEBAPP_REVERSEPROXY_BACKEND: "http://fylr.localhost:8082"
      FYLR_SERVICES_API_ADDR: ":8081"
      FYLR_SERVICES_BACKEND_ADDR: ":8082"
      FYLR_EXECSERVER_ADDRESSES: '["http://execserver:8070/?pretty=true"]'
      FYLR_EXECSERVER_CALLBACKBACKENDINTERNALURL: "http://fylr.localhost:8082"
      FYLR_EXECSERVER_CALLBACKAPIINTERNALURL: "http://fylr.localhost:8081"
      FYLR_ELASTIC_ADDRESSES: '["http://fylr-elastic:9200"]'
      FYLR_S3_ENDPOINT: "fylr-minio:9000"
      FYLR_DB_DRIVER: "sqlite3"
      FYLR_DB_DSN: "/fylr/files/database/fylr.db?_foreign_keys=1&&_busy_timeout=60000"
      FYLR_LOGGER_LEVEL: info
      # FYLR_ELASTIC_LOGGER: "Text"
      FYLR_LOGGER_TIMEFORMAT: "2006-01-02T15:04:05Z07:00"
    ports:
      - "8080:8080" # webfrontend
    depends_on:
      - fylr-elastic
      - fylr-minio
      - execserver
    networks:
      - fylr
    volumes:
      - "./config/fylr:/fylr/config"
      - "./data/sqlite:/fylr/files/database"

networks:
  fylr: