version: '3'
services:
  elasticsearch:
    image: docker.fylr.io/fylr/elasticsearch:latest
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - discovery.type=single-node
      - network.publish_host=0.0.0.0
      - cluster.routing.allocation.disk.watermark.low=2gb
      - cluster.routing.allocation.disk.watermark.high=1gb
      - cluster.routing.allocation.disk.watermark.flood_stage=500mb
      - indices.breaker.total.use_real_memory=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "./fylr/data/elastic:/usr/share/elasticsearch/data"
    networks:
      - fylr

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: 'fylr'
      POSTGRES_USER: 'fylr'
      POSTGRES_PASSWORD: 'fylr'
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "./fylr/data/postgres:/var/lib/postgresql/data"
    depends_on:
      - elasticsearch
    networks:
      - fylr

  minio:
    image: "minio/minio"
    container_name: "minio"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    volumes:
      - "./fylr/data/minio:/data"
    command: server /data
    depends_on:
      - elasticsearch
      - postgres
    networks:
      - fylr

  fylr-server-postgres:
    image: "docker.fylr.io/fylr/fylr:develop"
    container_name: fylr-server-postgres
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - elasticsearch
      - postgres
      - minio
    networks:
      - fylr
#    volumes:
#      - "./fylr/config/fylr.yml:/fylr/config/fylr.yml"

networks:
  fylr: