fylr:
  debug:
    skipTerms: false

  logger:
    noColor: true

  db:
    maxOpenConns: 20
    maxIdleConns: 10

  s3:
    accessKeyID: "minio"
    secretAccessKey: "minio123"
    bucketLocation: "us-east-1"
    ssl: false

  elastic:
    parallel: 4
    maxMem: 100mb
    objectsPerJob: 1000

  execserver:
    parallel: 2
    pluginJobTimeoutSec: 240
    connectTimeoutSec: 120

  plugins:
    - "/fylr/files/plugins/easydb"
    - "/fylr/files/plugins/fylr/example"
    - "/fylr/files/plugins/fylr/dev-day-plugin-example"

  allowpurge: true

  resources: "/fylr/files/resources"

  services:
    webapp:
      path: "/fylr/files/webfrontend"
      oauth2:
        clientID: web-client
        clientSecret: foo

    api:
      oauth2Server:
        clients:
          web-client:
            clientID: web-client
            clientSecret: $2y$16$MDOkFjSNZdfnVwA3cZSOjuZP8DPshwAda7T99GhLLqff8KyGYvZ4K
            redirectURL: http://fylr.localhost:8080/oauth2/callback
            scopes: ["read", "write", "offline"]
          app-client:
            clientID: app-client
            clientSecret: $2y$12$vHCyS42d0RpICdKoXKP0J.w1cschxjf.Ln43I9NYyl1u0W7vevjQS
            redirectURL: fylr.app.scheme:///
            scopes: ["read", "write", "offline"]

    backend:
      inspect:
        backup:
          path: /tmp/fylrctrl
          fylrctl: fylrctl
          psql: psql
          sqlite3: sqlite3

    execserver:
      tempDir: /tmp/fylr
      waitgroups:
        a:
          processes: 6
        b:
          processes: 4
        c:
          processes: 6
      services:
        mainbin:
          waitgroup: b
          commands:
            node:
              prog: "main.bin"
        node:
          waitgroup: b
          commands:
            node:
              prog: "node"
        convert:
          waitgroup: a
          commands:
            convert:
              prog: "convert"
              env:
                - "OMP_NUM_THREADS=2"
              startupCheck:
                args:
                  - "-version"
                regex: "Version: ImageMagick 7..*?https://imagemagick.org"
            composite:
              prog: "composite"
              env:
                - "OMP_NUM_THREADS=2"
              startupCheck:
                args:
                  - "-version"
                regex: "Version: ImageMagick 7..*?https://imagemagick.org"
            fylr_metadata:
              prog: "fylr_metadata"
        ffmpeg:
          waitgroup: a
          commands:
            ffmpeg:
              prog: ffmpeg
              startupCheck:
                args:
                  - "-version"
                regex: "ffmpeg version 4[\\.0-9]+ Copyright"
            ffprobe:
              prog: ffprobe
              startupCheck:
                args:
                  - "-version"
                regex: "ffprobe version 4[\\.0-9]+ Copyright"
            convert:
              prog: "convert"
              env:
                - "OMP_NUM_THREADS=2"
              startupCheck:
                args:
                  - "-version"
                regex: "Version: ImageMagick 7..*?https://imagemagick.org"
            composite:
              prog: "composite"
              env:
                - "OMP_NUM_THREADS=2"
              startupCheck:
                args:
                  - "-version"
                regex: "Version: ImageMagick 7..*?https://imagemagick.org"
            fylr_metadata:
              prog: "fylr_metadata"
        soffice:
          waitgroup: c
          commands:
            soffice:
              prog: soffice
              startupCheck:
                args:
                  - "--headless"
                  - "--invisible"
                  - "--version"
                regex: "LibreOffice 7[.0-9]+"
            convert:
              prog: "convert"
              env:
                - "OMP_NUM_THREADS=2"
              startupCheck:
                args:
                  - "-version"
                regex: "Version: ImageMagick 7..*?https://imagemagick.org"
            composite:
              prog: "composite"
              env:
                - "OMP_NUM_THREADS=2"
              startupCheck:
                args:
                  - "-version"
                regex: "Version: ImageMagick 7..*?https://imagemagick.org"
            fylr_metadata:
              prog: "fylr_metadata"
        pdf2pages:
          waitgroup: a
          commands:
            pdf2pages:
              prog: "pdf2pages"
            fylr_metadata:
              prog: "fylr_metadata"
        xslt:
          waitgroup: a
          commands:
              xsltproc:
                prog: "xsltproc"
        copy:
          waitgroup: a
          commands:
                copy:
                  prog: "copy"
        metadata:
          waitgroup: a
          commands:
            fylr_metadata:
              prog: "fylr_metadata"
            ffprobe:
              prog: ffprobe
              startupCheck:
                args:
                  - "-version"
                regex: "ffprobe version 4[\\.0-9]+ Copyright"
        iiif:
          waitgroup: a
          commands:
            iiif_im:
              prog: "iiif_im"
              startupCheck:
                args:
                  - "-version"
                regex: "Version v*"