fylr:
  name: postgres
  externalURL: "http://fylr.localhost:8080"

  debug:
    skipTerms: false

  logger:
    format: "console"
    level: info
    timeFormat: "2006-01-02T15:04:05Z07:00"
    noColor: true
    addHostname: false

  db:
    maxOpenConns: 20
    maxIdleConns: 10

  s3:
    accessKeyID: "minio"
    secretAccessKey: "minio123"
    bucketLocation: "us-east-1"
    ssl: false
    endpoint: "fylr-minio:9000"

  elastic:
    parallel: 4
    maxMem: 100mb
    objectsPerJob: 1000
    addresses:
      - "http://fylr-elastic:9200"

  execserver:
    parallel: 2
    pluginJobTimeoutSec: 240
    connectTimeoutSec: 120
    addresses:
      - http://fylr.localhost:8070/?pretty=true
    callbackBackendInternalURL: "http://fylr.localhost:8082"
    callbackApiInternalURL: "http://fylr.localhost:8081"

  plugins:
    - "/fylr/files/plugins/easydb"
    - "/fylr/files/plugins/fylr/example"
    - "/fylr/files/plugins/fylr/dev-day-plugin-example"

  allowpurge: true

  resources: "/fylr/files/resources"

  services:
    webapp:
      addr: ":8080"
      path: "/fylr/files/webfrontend"
      oauth2:
        clientID: web-client
        clientSecret: foo
      reverseProxy:
        api: "http://fylr.localhost:8081"
        backend: "http://fylr.localhost:8082"

    api:
      addr: ":8081"
      oauth2Server:
        clients:
          web-client:
            clientID: web-client
            clientSecret: $2y$16$MDOkFjSNZdfnVwA3cZSOjuZP8DPshwAda7T99GhLLqff8KyGYvZ4K
            redirectURIs: 
              - http://fylr.localhost:8080/oauth2/callback
            scopes: ["read", "write", "offline"]
          app-client:
            clientID: app-client
            clientSecret: $2y$12$vHCyS42d0RpICdKoXKP0J.w1cschxjf.Ln43I9NYyl1u0W7vevjQS
            redirectURIs: 
              - fylr.app.scheme:///
            scopes: ["read", "write", "offline"]

    backend:
      addr: ":8082"
      inspect:
        backup:
          path: /tmp/fylrctrl
          fylrctl: fylrctl
          psql: psql
          sqlite3: sqlite3

    execserver:
      addr: ":8070"
      tempDir: /tmp/fylr
      waitgroups:
        a:
          processes: 6
        b:
          processes: 4
        c:
          processes: 6
      services:
        mainbin:
          waitgroup: b
          commands:
            node:
              prog: "main.bin"
        node:
          waitgroup: b
          commands:
            node:
              prog: "node"
        convert:
          waitgroup: a
          commands:
            convert:
              prog: "convert"
              env:
                - "OMP_NUM_THREADS=2"
              startupCheck:
                args:
                  - "-version"
                regex: "Version: ImageMagick 7..*?https://imagemagick.org"
            composite:
              prog: "composite"
              env:
                - "OMP_NUM_THREADS=2"
              startupCheck:
                args:
                  - "-version"
                regex: "Version: ImageMagick 7..*?https://imagemagick.org"
            fylr_metadata:
              prog: "fylr_metadata"
        ffmpeg:
          waitgroup: a
          commands:
            ffmpeg:
              prog: ffmpeg
              startupCheck:
                args:
                  - "-version"
                regex: "ffmpeg version 4[\\.0-9]+ Copyright"
            ffprobe:
              prog: ffprobe
              startupCheck:
                args:
                  - "-version"
                regex: "ffprobe version 4[\\.0-9]+ Copyright"
            convert:
              prog: "convert"
              env:
                - "OMP_NUM_THREADS=2"
              startupCheck:
                args:
                  - "-version"
                regex: "Version: ImageMagick 7..*?https://imagemagick.org"
            composite:
              prog: "composite"
              env:
                - "OMP_NUM_THREADS=2"
              startupCheck:
                args:
                  - "-version"
                regex: "Version: ImageMagick 7..*?https://imagemagick.org"
            fylr_metadata:
              prog: "fylr_metadata"
        soffice:
          waitgroup: c
          commands:
            soffice:
              prog: soffice
              startupCheck:
                args:
                  - "--headless"
                  - "--invisible"
                  - "--version"
                regex: "LibreOffice 7[.0-9]+"
            convert:
              prog: "convert"
              env:
                - "OMP_NUM_THREADS=2"
              startupCheck:
                args:
                  - "-version"
                regex: "Version: ImageMagick 7..*?https://imagemagick.org"
            composite:
              prog: "composite"
              env:
                - "OMP_NUM_THREADS=2"
              startupCheck:
                args:
                  - "-version"
                regex: "Version: ImageMagick 7..*?https://imagemagick.org"
            fylr_metadata:
              prog: "fylr_metadata"
        pdf2pages:
          waitgroup: a
          commands:
            pdf2pages:
              prog: "pdf2pages"
            fylr_metadata:
              prog: "fylr_metadata"
        xslt:
          waitgroup: a
          commands:
              xsltproc:
                prog: "xsltproc"
        copy:
          waitgroup: a
          commands:
                copy:
                  prog: "copy"
        metadata:
          waitgroup: a
          commands:
            fylr_metadata:
              prog: "fylr_metadata"
            ffprobe:
              prog: ffprobe
              startupCheck:
                args:
                  - "-version"
                regex: "ffprobe version 4[\\.0-9]+ Copyright"
        iiif:
          waitgroup: a
          commands:
            iiif_im:
              prog: "iiif_im"
              startupCheck:
                args:
                  - "-version"
                regex: "Version v*"
